name: internshala
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.6
  json_annotation: ^4.9.0
  cached_network_image: ^3.3.1
  get: ^4.6.6
  http: ^1.2.1

dev_dependencies:
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.0


flutter:

  assets:
    - assets/

  uses-material-design: true

 