List<String> durations = [
  '1 months',
  '2 months',
  '3 months',
  '4 months',
  '6 months',
  '12 months',
  '24 months',
  '36 months'
];

List<String> cities = [
  "Delhi",
  "Mumbai",
  "Kolkata",
  "Bangalore",
  "Chennai",
  "Hyderabad",
  "Pune",
  "Ahmedabad",
  "Surat",
  "Lucknow",
  "Jaipur",
  "Kanpur",
  "Mirzapur",
  "Nagpur",
  "Ghaziabad",
  "Supaul",
  "Vadodara",
  "Rajkot",
  "Visakhapatnam",
  "Indore",
  "Thane",
  "Bhopal",
  "Pimpri-Chinchwad",
  "Patna",
  "Bilaspur",
  "Ludhiana",
  "Agra",
  "Madurai",
  "Jamshedpur",
  "Prayagraj",
  "Nashik",
  "Faridabad",
  "Meerut",
  "Jabalpur",
  "Kalyan",
  "Vasai-Virar",
  "Najafgarh",
  "Varanasi",
  "Srinagar",
  "Aurangabad",
  "Dhanbad",
  "Amritsar",
  "Aligarh",
  "Guwahati",
  "Howrah",
  "Ranchi",
  "Gwalior",
  "Chandigarh",
  "Haldwani",
  "Vijayawada",
  "Jodhpur",
  "Raipur",
  "Kota",
  "Bhayandar",
  "Loni",
  "Ambattur",
  "Salt Lake City",
  "Bhatpara",
  "Kukatpally",
  "Dasarahalli",
  "Muzaffarpur",
  "Oulgaret",
  "New Delhi",
  "Tiruvottiyur",
  "Puducherry",
  "Byatarayanapura",
  "Pallavaram",
  "Secunderabad",
  "Shimla",
  "Puri",
  "Murtazaabad",
  "Shrirampur",
  "Chandannagar",
  "Sultanpur Mazra",
  "Krishnanagar",
  "Barrackpore",
  "Bhalswa Jahangirpur",
  "Nangloi Jat",
  "Balasore",
  "Dalupura",
  "Yelahanka",
  "Titagarh",
  "Dum Dum",
  "Bansberia",
  "Madhavaram",
  "Abbigeri",
  "Budge Budge",
  "Garhi",
  "Meerpet",
  "Nerkundram",
  "Kendrapara",
  "Sijua",
  "Manali",
  "Kankuria",
  "Chakapara",
  "Pappakurichi",
  "Herohalli",
  "Madipakkam",
  "Sabalpur",
  "Bauria",
  "Salua",
  "Chikkabanavara",
  "Jalahalli",
  "Chinnasekkadu",
  "Jethuli",
  "Naktala",
  "Pakri",
  "Hunasamaranahalli",
  "Hesaraghatta",
  "Bommayapalayam",
  "Gundur",
  "Punadih",
  "Hariladih",
  "Alawalpur",
  "Madnaikanahalli",
  "Bagalur",
  "Kadiganahalli",
  "Khanpur Zabti",
  "Mahuli",
  "Ziadah Kot",
  "Arshakunti",
  "Mirchi",
  "Sonudih",
  "Bayandhalli",
  "Sondekoppa",
  "Babura",
  "Madavar",
  "Kadabagere",
  "Nanmangalam",
  "Tollygunge",
  "Tarchha",
  "Belgharia",
  "Kammanahalli",
  "Ambapuram",
  "Sonnappanhalli",
  "Kedihatti",
  "Doddajeevanahalli",
  "Simli Murarpur",
  "Sonawan",
  "Devanandapur",
  "Tribeni",
  "Huttanhalli",
  "Nathupur",
  "Bally",
  "Vajarhalli",
  "Alijah Kotla",
  "Saino",
  "Shekhpura",
  "Chachohalli",
  "Andheri",
  "Narayanpur Kola",
  "Gyan Chak",
  "Kasgatpur",
  "Kitanelli",
  "Harchandi",
  "Santoshpur",
  "Bendravadi",
  "Kodagihalli",
  "Harna Buzurg",
  "Mailanhalli",
  "Sultanpur",
  "Adakimaranhalli"
];

List<String> profiles = [
  '.NET Development',
  '3D Printing',
  'Accounts',
  'Acting',
  'Aerospace Engineering',
  'Agriculture & Food Engineering',
  'Analytics',
  'Anchoring',
  'Android App Development',
  'Angular.js Development',
  'Animation',
  'Architecture',
  'Artificial Intelligence (AI)',
  'ASP.NET Development',
  'Audio Making/Editing',
  'Auditing',
  'Automobile Engineering',
  'Backend Development',
  'Bank',
  'Big Data',
  'Bioinformatics',
  'Biology',
  'Biotechnology Engineering',
  'Blockchain Development',
  'Blogging',
  'Brand Management',
  'Business Development',
  'Business/MBA',
  'CA Articleship',
  'CAD Design',
  'Campus Ambassador',
  'Chartered Accountancy (CA)',
  'Chemical Engineering',
  'Chemistry',
  'Cinematography',
  'Civil Engineering',
  'Client Servicing',
  'Cloud Computing',
  'CMA Articleship',
  'Commerce',
  'Company Secretary (CS)',
  'Computer Science',
  'Computer Vision',
  'Content Writing',
  'Copywriting',
  'Creative Design',
  'Creative Writing',
  'CS Articleship',
  'Culinary Arts',
  'Customer Service',
  'Cyber Security',
  'Data Entry',
  'Data Science',
  'Database Building',
  'Design',
  'Dietetics/Nutrition',
  'Digital Marketing',
  'E-commerce',
  'Editorial',
  'General Management',
  'Government',
  'Graphic Design',
  'Hospitality',
  'Hotel Management',
  'Human Resources (HR)',
  'Humanities',
  'Image Processing',
  'Industrial & Production Engineering',
  'Industrial Design',
  'Information Technology',
  'Instrumentation & Control Engineering',
  'Interior Design',
  'International',
  'Internet of Things (IoT)',
  'iOS App Development',
  'Java Development',
  'Javascript Development',
  'Journalism',
  'Law',
  'Legal Research',
  'Machine Learning',
  'Manufacturing Engineering',
  'Market/Business Research',
  'Marketing',
  'Material Science',
  'Mathematics',
  'Mathematics & Computing',
  'Mechanical Engineering',
  'Mechatronics',
  'Media',
  'Medicine',
  'Merchandise Design',
  'Mobile App Development',
  'Motion Graphics',
  'Music',
  'Network Engineering',
  'NGO',
  'Node.js Development',
  'Operations',
  'Petroleum Engineering',
  'PHP Development',
  'Pharmaceutical',
  'Photography',
  'Physics',
  'Political/Economics/Policy Research',
  'Product Management',
  'Programming',
  'Project Management',
  'Proofreading',
  'Psychology',
  'Public Relations (PR)',
  'Python/Django Development',
  'Quality Analyst',
  'Recruitment',
  'Robotics',
  'Ruby on Rails',
  'Sales',
  'Science',
  'Search Engine Optimization (SEO)',
  'Social Media Marketing',
  'Social Work',
  'Software Development',
  'Software Testing',
  'Sports',
  'Statistics',
  'Stock/Market Trading',
  'Strategy',
  'Subject Matter Expert (SME)',
  'Supply Chain Management (SCM)',
  'Talent Acquisition',
  'Teaching',
  'Telecalling',
  'Transcription',
  'Translation',
  'Travel & Tourism',
  'UI/UX Design',
  'Video Making/Editing',
  'Videography',
  'Volunteering',
  'Web Development',
  'Wordpress Development',
];

String base_url = "Add the url here";
